### PR TITLE
converted mozmill test to marionette test_enable_privilege.py bug 113262...

### PR DESCRIPTION
**Pull request by sarvjeetsinghghotra**
...4

### CODE REVIEW

**Comment by whimboo** [comment]
@sarvjeetsinghghotra do you have any problems with the PR you need help with?

**Comment by sarvjeetsinghghotra** [comment]
Not yet.

**Comment by sarvjeetsinghghotra** [comment]
I want to participate in GSOC 2015 with this idea of converting mozmill tests to marionette with you be my mentor. I wanted to talk to you about this, how should I contact you email or anything else? If mail then email ID please.

**Comment by whimboo** [comment]
@sarvjeetsinghghotra, I'm sad to say that Google decided to not include Mozilla for GSOC 2015. So this won't be an option. Sorry.

**Comment by whimboo** [comment]
So this PR has been closed. Shouldn't we reopen it? Or what is your intent to continue here?

**Comment by sarvjeetsinghghotra** [comment]
@whimboo My immediate aim is to participate in GSOC 2015 , so I will be inactive for some time. But surely join later especially to help with m21 project.Sorry.

**Pull request closed without merging**
