### PR TITLE
Bug 1180429 - Missing headers for classes in TOC of docs

### PR DESCRIPTION
**Pull request by utvar**
Hi, @whimboo, this changes files in the docs/ui directory so that all classes are listed in the TOC (under the library containing them). If you like this, I could do the same for the docs/api directory.

### CODE REVIEW

**Comment by whimboo** [comment]
I think that's a good idea. So yes, if we also miss those headings for api modules, lets also get them added there. Btw. does a bug in bugzilla exist for those changes? We usually track review process over there.

**Comment by utvar** [comment]
Thanks for the feedback, @whimboo. There doesn't seem to be a bug report on Bugzilla for this. Should I enter one there under Mozilla QA? Then, would you prefer that I reference the bug in a comment, or in the title of this PR?

**Comment by utvar** [comment]
It looks like the Travis build failed because of test failures, not because of my code.

**Comment by chmanchester** [comment]
@utvar, this looks good. Please squash your commits into a single commit and update the commit message to reflect the bug number and reviewer so I can merge. Thanks!

**Comment by utvar** [comment]
@chmanchester, here is the updated commit. Do you want me to change the PR title to match that of the Bug and commit message?

**Comment by whimboo** [comment]
@utvar thanks for your contribution! If you are interested in something else please let us know.

**Pull request merged**
