### PR TITLE
Rename repository to firefox-ui-tests (#44)

### PR DESCRIPTION
**Pull request by whimboo**
@chmanchester mind having a look?

### CODE REVIEW

**Comment by chmanchester** [comment]
I'm not a fan of how this looks: I know it's more or less consistent with gaiatest, but firefoxtests seems too general. Is firefox_ui_tests too ugly?

**Comment by whimboo** [comment]
Chris the CLI is only temporary. At the end we will have a couple of different entry scripts.

**Comment by chmanchester** [comment]
README.md will want updates with this as well.

**Comment by whimboo** [comment]
@chmanchester I fixed the readme file, and updated the console command to `firefox-ui-tests`. If you don't mind I would keep the `firefoxtests` subfolder regarding all the underscores we would have to use. As alternative we could move out the harness to `/harness` which would make it easier later to uncouple the dependencies also for the puppeteer modules. I could do that in a follow-up issue.

**Comment by chmanchester** [comment]
You've pointed out that the repository structures here will likely change as we progress, so this is probably good for now.

**Comment by whimboo** [comment]
That is true, and we might have to find a solution soon, before we have to update too many of the tests. Maybe I can do that soon for the harness pieces. Thanks for all your comments!

**Comment by whimboo** [comment]
I squashed the commits and merged the PR as https://github.com/mozilla/firefox-ui-tests/commit/9109e23acf38ae2ac0ac0dca6e4f9b74a8aa96a7.

**Pull request closed without merging**
