### PR TITLE
Bug 1131712 - Calling find_element() should use constants from marionette.By instead of hard-coded values. r=whimboo

### PR DESCRIPTION
**Pull request by heisenberg-**

### CODE REVIEW

**Comment by whimboo** [comment]
@heisenberg- this PR needs a rebase from master given that it can no longer be merged. Please do and repush. Thanks.

**Comment by whimboo** [comment]
Please do not close this PR. You can still push a rebased versoin of your branch with the -f option.

**Comment by whimboo** [comment]
Please let me know if you have problems in pushing your changes.

**Comment by heisenberg-** [comment]
I am new to github. I don't know what i am doing.

**Comment by whimboo** [comment]
So you have to rebase your integration branch by merging in the latest chagnes from master. You do that by running `git rebase master` while your integration branch is checked out. Once done and possible merge conflicts fixed, you can push your updates as usual to our remote branch. The PR will be updated automatically.

It would be easier if you can join us on IRC so we could have a real-time conversation.

**Comment by heisenberg-** [comment]
@whimboo i have applied `git rebase master`, try merging now.

**Comment by heisenberg-** [comment]
@whimboo Conflict resolved and Build passed. Try merge now

**Comment by whimboo** [comment]
Doing a grep for `find_element('` across the repository, I can find some more line which need an update:

./firefox_puppeteer/ui/tabbar.py:        return self.toolbar.find_element('anon attribute', {'anonid': 'tabs-newtab-button'})
./firefox_puppeteer/ui/tabbar.py:        return self.tab_element.find_element('anon attribute', {'anonid': 'close-button'})
./firefox_puppeteer/ui/tabbar.py:                                     .find_element('anon attribute',
./firefox_puppeteer/ui/toolbars.py:        parent = self.urlbar.find_element('anon attribute', {'anonid': 'textbox-input-box'})
./firefox_puppeteer/ui/toolbars.py:        return parent.find_element('anon attribute', {'anonid': 'input-box-contextmenu'})
./firefox_puppeteer/ui/toolbars.py:        return self.urlbar.find_element('anon attribute', {'anonid': 'historydropmarker'})
./firefox_puppeteer/ui/toolbars.py:        return self.urlbar.find_element('anon attribute', {'anonid': 'input'})
./firefox_puppeteer/ui/toolbars.py:        return self.popup.find_element('anon attribute',

**Comment by heisenberg-** [comment]
@whimboo `anon attribute` is not available in By.py

**Comment by whimboo** [comment]
Good catch! That's indeed missing in Marionette. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1133718 for it. Until we have it, this PR looks to be complete. I will get it merged later. Thanks!

**Comment by whimboo** [comment]
PR has been merged as https://github.com/mozilla/firefox-ui-tests/commit/c3ffa4036bfc255f8437b74bbdb3c4d93806c217.

**Pull request closed without merging**
