### PR TITLE
Bug 1227570 - Remove support of the --installer command line option

### PR DESCRIPTION
**Pull request by whimboo**

### CODE REVIEW

**Comment by mjzffr** [comment]
@whimboo This merge looks fine upon quick examination. I assume there were conflicts, so are there any sections in particular that I should inspect more closely? Thanks.

**Comment by whimboo** [comment]
It's mainly because the conflicts. I also removed the additional locale as used for nightly and aurora. So this is mostly affecting travis runs. Sadly Travis status shows queuing issues at the moment so that our PR doesn't get tested. If you think all is fine I will wait until tomorrow once Travis passed (or not given the unrelated ui changes of the upcoming next beta).

**Comment by whimboo** [comment]
Travis build completed now. Visible failures are known to be fixed once we get the new beta build. I'm going to land this patch now.

**Comment by whimboo** [comment]
Merged PR as https://github.com/mozilla/firefox-ui-tests/commit/2ea977168113a137c7ae342d46ce87c7865ff5a8.

**Pull request closed without merging**
