### PR TITLE
Bug 1137122 - Bump dependency for marionette-client to v0.9. r=automatedtester

### PR DESCRIPTION
**Pull request by whimboo**
This is the fix so we can bump to marionette-client 0.9. @AutomatedTester can you please review it? Thanks.

### CODE REVIEW

**Comment by whimboo** [comment]
Travis is still failing because the changes for marionette-driver as not on mozilla-central nor gecko-dev yet.

**Comment by AutomatedTester** [comment]
r+

**Comment by whimboo** [comment]
Travis detected a failure because I missed to pull from upstream master first, which had a new test. I fixed the failures and pushed the new commit. Awaiting travis results before merging the branch.

**Comment by whimboo** [comment]
PR has been merged as https://github.com/mozilla/firefox-ui-tests/commit/e3fe727b963093812703854fa7e7532eccc36faf

**Pull request closed without merging**
